language: go
install:
- go get -v github.com/spf13/hugo
- bower install
- pip install awscli
script: make build
after_success: make deploy
branches:
  only:
  - master
env:
  global:
  - secure: BNX8Hq0yhUBn89Btf7TrKee3M1dFW9dyYVWEOFemFs6Ts2fcQ1atzXBvuQmsiUhpwg2CsBDTmywZ6fq8BZ58jcer6KlDQ6FxHKoGIQsEk4jcb0NBaDnfixhTMsX1/H990wgxUNtN0H+U4g2BAy2ny12ybm/1b4lg1+CNXSClTnU=
  - secure: f0NoscHVmEJ+5NEi22Tsvm7/1TcwTZ+fzvUg27JvA6HMJsjtjqQQ0/SWXFd1KPShem66mThoGIEQFwvcQPIsi0PXeOF8LbPfl9vvXSdAHlpsDX6GwQDJlZfQKbFmIhRuH6ut83z+BmGadEOMSTBJqv8KVRiFtybOjD5R8NUrM74=
